name: Update
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: "Configure AWS Credentials Action for GitHub Actions"
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::691906383352:role/github-actions-role
          aws-region: us-east-2
           
      - name: "Cloud Front Delete Cache"
        run: aws cloudfront create-invalidation --distribution-id ES451F0S2WX32 --paths '/*'



    


        
            



