jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: "Configure AWS Credentials" Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-secret-access-key: $ffsecrets.AWS_SECRET_ACCESS_KEY}} 
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}} 
          aws-region: us-east-2
      - name: "Update S3 Bucket"
        with:
          

        
            



